### ISSUE TITLE
Hi, @MCUnderground.

### ISSUE THREAD

**Issue by KyePlayzMCPE** [KyePlayzMCPE/LEET-Party#1]
@MCUnderground, Hi. I'm needing your help with the code, so check out plugin.yml for more.

**Comment by MCUnderground** [comment]
Make base of a code

**Comment by KyePlayzMCPE** [comment]
I mean, work on Plugin.yml for me and the PHP Files..

**Comment by thelucyclub** [comment]
Do not demand things. There is no free lunch in the world. Somewhere, someone needs to pay.
