### ISSUE TITLE
do you even know how to make a plugin?

### ISSUE THREAD

**Issue by jasonw4331** [KyePlayzMCPE/LEET-Party#2]
what is your plan for this plugin? how do you want it to work?

**Comment by MCUnderground** [comment]
Idk

**Comment by jasonw4331** [comment]
not you @MCUnderground :P

**Comment by TylerGames** [comment]
Wait, will this be for LEET-Servers???

**Comment by MCUnderground** [comment]
No lol

**Comment by TylerGames** [comment]
How will we host it on a leet server then?

**Comment by KyePlayzMCPE** [comment]
It'll be for LEET Servers

**Comment by KyePlayzMCPE** [comment]
It's a LEET Party plugin, so here:
/lp add <name> | Add a player to Party, if already in a party, don't let them add
/lp remove <name> | Remove a player
/lp teleport | Teleports your whole party to you
/lp delete | Delerte a party
/lp create <name> | Create a party, like faction, and include the party name in rank

**Comment by KyePlayzMCPE** [comment]
The rank would show LP:<status>
So: /lp create MYP
Rank: LP:MYP
No party created = LP:None

**Comment by KyePlayzMCPE** [comment]
It's for LEET, and I can inform them of this

**Comment by thelucyclub** [comment]
@KyePlayzMCPE Nice idea. But do you know PHP?

**Comment by KyePlayzMCPE** [comment]
That's why I'm...needing your help. I tried to do plugin.yml. Is it right, now? Anyway, we're not doing the rank part, I've spoke to LEET.

**Comment by jasonw4331** [comment]
the plugin.yml is incorrectly formatted

**Comment by HBIDamian** [comment]
_sigh_ That was... well..... its... well, you know.... False Start!

**Comment by jasonw4331** [comment]
@KyePlayzMCPE Please learn how to make a plugin before you try to correct what i did to correct your mistake

**Comment by TylerGames** [comment]
This would be nice to code though, but.. learn to code a but more @KyePlayzMCPE

**Comment by thelucyclub** [comment]
I got some command bases done, and did the entire /lp help command
