### ISSUE TITLE
Helping on How To Code

### ISSUE THREAD

**Issue by Taki21** [KyePlayzMCPE/LEET-Party#3]
https://forums.imagicalmine.net/threads/imagicalmine-how-to-create-plugins-2nd-edition.794/

**Comment by Taki21** [comment]
IF u need help use that as a reference

**Comment by KyePlayzMCPE** [comment]
Thanks.. Great Tut! I don't understand what the plugin base would be tho.

**Comment by MCUnderground** [comment]
@Taki21 is everywhere lol. He never make stuff in lostteam :( bad taki

**Comment by KyePlayzMCPE** [comment]
XD

**Comment by KyePlayzMCPE** [comment]
:S

**Comment by MCUnderground** [comment]
Im gonna hunt him down in im forums

**Comment by KyePlayzMCPE** [comment]
What forums?

**Comment by Taki21** [comment]
@MCUnderground Sorry : ( Everybody was " killing me" recentlly...XD

**Comment by Taki21** [comment]
`$entities = count($level->getEntities);`
`foreach($entities as $entity){`
`$entity->setHealth(0);`
`}`
To kill all entities in world

**Comment by MCUnderground** [comment]
@Taki21 but ill rape you 💯

**Comment by Taki21** [comment]
)_(

**Comment by MCUnderground** [comment]
Oh no
if(v == Taki21){
finish();
}

**Comment by Taki21** [comment]
xD

**Comment by Taki21** [comment]
if(this.mcunderground === null){
this.getServer().ban(this.mcunderground);
return true;
}

**Comment by Taki21** [comment]
> #### Taki21 Said:
> 
> if(this.mcunderground === null){
> this.getServer().ban(this.mcunderground);
> **return true;**
> }

LOL! TRUE FOR YER BAN xD

**Comment by remotevase** [comment]
Or why dont you use

# _**[howtocode.ml](http://howtocode.ml)**_

Almost the same exact lessons, but completely different organization. I feel that the website is more friendly

**Comment by Taki21** [comment]
or that lol
