### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Alpha-PR** [KyePlayzMCPE/LEET-Party#4]
Kye has decided to stop developing this, but I'm leaving this to you, to do what you want with it.

**Comment by Taki21** [comment]
ME?!

**Comment by Alpha-PR** [comment]
...

**Comment by Taki21** [comment]
`Call To A Member Function "...()" on Null on Line 433,324,234,243,567 in src/null/null.php`
`Unexpected "..." or Syntax Error on Line 1,738 in null.php`

**Comment by Alpha-PR** [comment]
Taki,
I've invited you to a plugin

**Comment by Taki21** [comment]
kk

**Comment by Taki21** [comment]
help soon

**Comment by Taki21** [comment]
going outside now xD

**Comment by jasonw4331** [comment]
I don't think this plugin could go anywhere because of how leet makes their own plugins rather than import other peoples

**Comment by Taki21** [comment]
what do u mean?

**Comment by MCUnderground** [comment]
Leet wont use this plugin prob..

**Comment by Jiang2542** [comment]
For sure

**Comment by Alpha-PR** [comment]
Anyway, forums are down
